### ISSUE TITLE
Issue with Learn 

### ISSUE THREAD

**Issue by mrarthurwhite** [learn-co-curriculum/fewpjs-introducing-the-dom-and-just-enough-javascript#10]
The tech coach mentioned that it was an issue with learn and flatiron and they would resolve it. I get this error whenever I type learn.

```
npm WARN javascript-lab@1.0.0 No repository field.
npm WARN javascript-lab@1.0.0 license should be a valid SPDX license expression

added 210 packages from 625 contributors and audited 2129 packages in 106.023s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> javascript-lab@1.0.0 test /mnt/c/Users/Numa/dev/flatiron/labs/fewpjs-dom-editing-lab-online-web-ft-120919
> mocha -R mocha-multi --reporter-options spec=-,json=.results.json



  1) "before all" hook

  0 passing (6s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:312:18)
      at process._tickCallback (internal/process/next_tick.js:61:11)



npm ERR! Test failed.  See above for more details.
[22:21:13]  fewpjs-dom-editing-lab-online-web-ft-120919 (master)
```

**Comment by Sdcrouse** [comment]
@mrarthurwhite I hate to say this, but I think you raised this issue on the wrong lesson. This isn't a lab. Did you mean to raise this issue on the lesson right before it?

**Comment by mrarthurwhite** [comment]
Yes it may have been a lab before it.

**Comment by Sdcrouse** [comment]
OK. It looks like the same issue I had with it, if it's the lab that I'm thinking of. I raised an issue and opened a pull request on it yesterday.

**Comment by mrarthurwhite** [comment]
Ok this ought to be marked as resolved. Here is the solution for it : 
https://help.learn.co/en/articles/567920-error-timeout-of-2000ms-exceeded

>  follow these steps:
> 
> 1. Open the package.json  file in the directory for your lab.
> 2. Locate the "scripts"  key, and the "test"  key within "scripts" 
> 3. After mocha , add --timeout 5000  so that the key looks like this:  "scripts": { "test": "mocha --timeout 5000 -R mocha-multi --reporter-options nyan=-,json=.results.json" }

**Comment by Sdcrouse** [comment]
Cool! By the way, since you raised the issue, you can go ahead and resolve it yourself, if you want.

**Comment by mrarthurwhite** [comment]
So note above that this has been resolved.
