### ISSUE TITLE
Code example block does not match others

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/fewpjs-introducing-the-dom-and-just-enough-javascript#2]
The code example block for template literals breaks the conventions that were set with earlier examples (using `//=>` for return values, using multiple lines, etc). See below:

```
    let pool = 'trouble'`Ya got ${pool}, ${pool}, ${pool}, ${pool}, ${pool}...`;
    ('Ya got trouble, trouble, trouble, trouble, trouble...');
```

Should be refactored to:

```
    let pool =  'trouble'
    //=> undefined
    `Ya got ${pool}, ${pool}, ${pool}, ${pool}, ${pool}...`;
    //=> 'Ya got trouble, trouble, trouble, trouble, trouble...'
```

**Comment by sgharms** [comment]
@AspenJames FWIW, you're always welcome to open the PR and skip the issue creation step. I can infer the issue usu. from the title / diff ;)

**Comment by AspenJames** [comment]
@sgharms sounds good! Thank you
