### ISSUE TITLE
Template literal example doesnt work. 

### ISSUE THREAD

**Issue by Dwake5** [learn-co-curriculum/fewpjs-introducing-the-dom-and-just-enough-javascript#4]
let pool = 'trouble'`Ya got ${pool}, ${pool}, ${pool}, ${pool}, ${pool}...`;
('Ya got trouble, trouble, trouble, trouble, trouble...');

Poorly presented and doesnt work.

**Comment by rrcobb** [comment]
Running the example in the console seems to work as presented. 

Could you add more detail as to what didn't work in the code?

**Comment by Dwake5** [comment]
The learn page has been updated since I posted that, so its no applicable. 

The lab does indeed now work at intended.

**Comment by rrcobb** [comment]
Awesome, thanks for the report!
