### ISSUE TITLE
.count isn't a javascript method?

### ISSUE THREAD

**Issue by Chungcha** [learn-co-curriculum/fewpjs-introducing-the-dom-and-just-enough-javascript#9]
Near the bottom at the **Explain That JavaScript Logs With console.log** section theres 

`for (let i = 0; i < slytherins.count; i = i + 1) {
  harry_potter.expelliarmus(slytherins[i]);
}` 

I couldnt run it in my console because it seems .count isn't a javascript method?  I think .length would work better?

**Comment by sgharms** [comment]
confirmed! Willfix!
